HRMS.Web/HRMS.Web/Areas/Admin/Controllers/AttendenceListController.cs
using HRMS.Models.Common;
using HRMS.Web.BusinessLayer;
using HRMS.Models.AttendenceList;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Results = HRMS.Models.Common.Results;
using Newtonsoft.Json;
using DocumentFormat.OpenXml.EMMA;
using Microsoft.AspNetCore.Mvc.Rendering;
using HRMS.Models.Company;
using HRMS.Models.LeavePolicy;
using DocumentFormat.OpenXml.Wordprocessing;
using HRMS.Models.DashBoard;
using DocumentFormat.OpenXml.Vml.Spreadsheet;
using HRMS.Models;

namespace HRMS.Web.Areas.Admin.Controllers
{
    [Area(Constants.ManageAdmin)]
    [Authorize]
    public class AttendenceListController : Controller
    {
        private readonly IConfiguration _configuration; 
        private readonly IBusinessLayer _businessLayer;
        public AttendenceListController(IConfiguration configuration, IBusinessLayer businessLayer)
        {
            _configuration = configuration;
            _businessLayer = businessLayer;
        }
        public IActionResult AttendenceListing()
        {
            Results results = new Results();
            return View(results);
        }
        [HttpPost]
        [AllowAnonymous]
        public JsonResult GetAllAttendenceList(string sEcho, int iDisplayStart, int iDisplayLength, string sSearch)
        {
            AttendanceInputParams attendenceListParams = new AttendanceInputParams();
             attendenceListParams.Month = DateTime.Now.Month;
            //attendenceListParams.Month =1;
            attendenceListParams.Year = DateTime.Now.Year;
            attendenceListParams.UserId = Convert.ToInt64(HttpContext.Session.GetString(Constants.EmployeeID));
            var data = _businessLayer.SendPostAPIRequest(attendenceListParams, _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.AttendenceList, APIApiActionConstants.GetTeamAttendanceForCalendar), HttpContext.Session.GetString(Constants.SessionBearerToken), true).Result.ToString();  
            var model = JsonConvert.DeserializeObject<AttendanceWithHolidays>(data);
            return Json(new { data = model });

        }
        public IActionResult Index(string id)
        {
            Attendance model = new Attendance();

            if (!string.IsNullOrEmpty(id))
            {
                model.ID = Convert.ToInt64(id);
                var data = _businessLayer.SendPostAPIRequest(model, _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.AttendenceList, APIApiActionConstants.GetAttendenceListID), HttpContext.Session.GetString(Constants.SessionBearerToken), true).Result.ToString();
                model = JsonConvert.DeserializeObject<HRMS.Models.Common.Results>(data).AttendanceModel;

            }

            HRMS.Models.Common.Results results = GetAllEmployees(Convert.ToInt64(HttpContext.Session.GetString(Constants.EmployeeID)));
            model.Employeelist = results.Employee;
            return View(model);
        }
        [HttpPost]
        public IActionResult Index(Attendance AttendenceListModel)
        {
            AttendenceListModel.WorkDate = AttendenceListModel.FirstLogDate;
            var data = _businessLayer.SendPostAPIRequest(AttendenceListModel, _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.AttendenceList, APIApiActionConstants.AddUpdateAttendace), HttpContext.Session.GetString(Constants.SessionBearerToken), true).Result.ToString();
            var result = JsonConvert.DeserializeObject<Result>(data);

            if (AttendenceListModel.ID > 0)
            {

                return RedirectToAction("AttendenceListing");/*Constants.Index, WebControllarsConstants.AttendenceList, new { id = AttendenceListModel.ID.ToString() });*/

            }
            else
            {
                return RedirectToActionPermanent(WebControllarsConstants.AttendenceListing, WebControllarsConstants.Attendance);

            }
        }
      
        public HRMS.Models.Common.Results GetAllEmployees(long EmployeeID)
        {
            HRMS.Models.Common.Results result = null;
            var data = "";
            if (HttpContext.Session.GetString(Constants.ResultsData) != null)
            {
                data = HttpContext.Session.GetString(Constants.ResultsData);
            }
            else
            {
                data = _businessLayer.SendGetAPIRequest("Common/GetAllEmployees?EmployeeID=" + EmployeeID, HttpContext.Session.GetString(Constants.SessionBearerToken), true).Result.ToString();
            }
            HttpContext.Session.SetString(Constants.ResultsData, data);
            result = JsonConvert.DeserializeObject<HRMS.Models.Common.Results>(data);
            return result;
        }

        [HttpGet]
        public IActionResult DeleteAttendanceDetails(int id)
        {
            Attendance model = new Attendance()
            {
                ID = id,
            };
            var data = _businessLayer.SendPostAPIRequest(model, _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.AttendenceList, APIApiActionConstants.DeleteAttendanceDetails), HttpContext.Session.GetString(Constants.SessionBearerToken), true).Result.ToString();
            if (data != null)
            {
                TempData[HRMS.Models.Common.Constants.toastType] = HRMS.Models.Common.Constants.toastTypeSuccess;
                TempData[HRMS.Models.Common.Constants.toastMessage] = data;
            }
            return RedirectToActionPermanent(WebControllarsConstants.AttendenceListing, WebControllarsConstants.Attendance);
        }


        [HttpGet]
        [AllowAnonymous] 
        public IActionResult AttendenceList()
        {            
            return View( );
        }
        [HttpGet]
        [AllowAnonymous]
        public IActionResult AttendenceCalendarList(int year, int month)
        {
            var employeeId = Convert.ToInt64(HttpContext.Session.GetString(Constants.EmployeeID));
            var employeeName = Convert.ToString(HttpContext.Session.GetString(Constants.FirstName));
            var employeeMiddleName = Convert.ToString(HttpContext.Session.GetString(Constants.MiddleName));
            var employeeLastName = Convert.ToString(HttpContext.Session.GetString(Constants.Surname));         
            var employeeFullName = string.Join(" ", new[] { employeeName, employeeMiddleName, employeeLastName }.Where(name => !string.IsNullOrWhiteSpace(name)));

            AttendanceInputParams models = new AttendanceInputParams
            {
                Year = year,
                Month = month,
                UserId = employeeId,
            };

            var data = _businessLayer.SendPostAPIRequest(models, _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.AttendenceList, APIApiActionConstants.GetAttendanceForMonthlyViewCalendar), HttpContext.Session.GetString(Constants.SessionBearerToken), true).Result.ToString();
            var model = JsonConvert.DeserializeObject<AttendanceWithHolidays>(data);

            return Json(new { data = model, employeeFullName = employeeFullName });
        }
    

    }



}

HRMS.Web/HRMS.Web/Areas/Employee/Controllers/AttendanceController.cs
using DocumentFormat.OpenXml.InkML;
using DocumentFormat.OpenXml.Office2010.Excel;
using DocumentFormat.OpenXml.Spreadsheet;
using DocumentFormat.OpenXml.Wordprocessing;
using HRMS.Models.AttendenceList;
using HRMS.Models.Common;
using HRMS.Models.DashBoard;
using HRMS.Models.Employee;
using HRMS.Models.Leave;
using HRMS.Models.MyInfo;
using HRMS.Models.ShiftType;
using HRMS.Models.User;
using HRMS.Web.BusinessLayer;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using OfficeOpenXml.FormulaParsing.Excel.Functions.Text;
using System;
using System.Linq;

namespace HRMS.Web.Areas.Employee.Controllers
{
    [Authorize]
    [Area(Constants.ManageEmployee)]
    //  [Authorize(Roles = (RoleConstants.HR + "," + RoleConstants.Admin + "," + RoleConstants.Employee + "," + RoleConstants.Manager + "," + RoleConstants.SuperAdmin))]
    public class AttendanceController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IBusinessLayer _businessLayer;
        private readonly ICheckUserFormPermission _CheckUserFormPermission;

        public AttendanceController(ICheckUserFormPermission CheckUserFormPermission, IConfiguration configuration, IBusinessLayer businessLayer)
        {
            _configuration = configuration;
            _businessLayer = businessLayer;
            _CheckUserFormPermission = CheckUserFormPermission;
        }

        public IActionResult AttendenceListing()
        {

            HRMS.Models.Common.Results results = new HRMS.Models.Common.Results();
            return View(results);
        }
        [HttpPost]
        [AllowAnonymous]
        public JsonResult GetAllAttendenceList(string sEcho, int iDisplayStart, int iDisplayLength, string sSearch)
        {
            AttendenceListInputParans attendenceListParams = new AttendenceListInputParans();
            attendenceListParams.ID = Convert.ToInt64(HttpContext.Session.GetString(Constants.ID));

            var data = _businessLayer.SendPostAPIRequest(attendenceListParams, _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.AttendenceList, APIApiActionConstants.GetAllAttendenceList), HttpContext.Session.GetString(Constants.SessionBearerToken), true).Result.ToString();
            var results = JsonConvert.DeserializeObject<HRMS.Models.Common.Results>(data);

            return Json(new { data = results.AttendenceList });

        }
        public IActionResult Index(string id)
        {

            Attendance model = new Attendance();
            if (!string.IsNullOrEmpty(id))
            {
                model.ID = Convert.ToInt64(id);
                var data = _businessLayer.SendPostAPIRequest(model, _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.AttendenceList, APIApiActionConstants.GetAttendenceListID), HttpContext.Session.GetString(Constants.SessionBearerToken), true).Result.ToString();
                model = JsonConvert.DeserializeObject<HRMS.Models.Common.Results>(data).AttendanceModel;
            }
            HRMS.Models.Common.Results results = GetAllEmployees(Convert.ToInt64(HttpContext.Session.GetString(Constants.EmployeeID)));
            model.Employeelist = results.Employee;
            return View(model);
        }

        public HRMS.Models.Common.Results GetAllEmployees(long EmployeeID)
        {
            HRMS.Models.Common.Results result = null;
            var data = "";
            if (HttpContext.Session.GetString(Constants.ResultsData) != null)
            {
                data = HttpContext.Session.GetString(Constants.ResultsData);
            }
            else
            {
                data = _businessLayer.SendGetAPIRequest("Common/GetAllEmployees?EmployeeID=" + EmployeeID, HttpContext.Session.GetString(Constants.SessionBearerToken), true).Result.ToString();
            }
            HttpContext.Session.SetString(Constants.ResultsData, data);
            result = JsonConvert.DeserializeObject<HRMS.Models.Common.Results>(data);
            return result;
        }

        [HttpPost]
        public IActionResult Index(AttendenceListModel AttendenceListModel)
        {
            if (ModelState.IsValid)
            {

                var data = _businessLayer.SendPostAPIRequest(AttendenceListModel, _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.AttendenceList, APIApiActionConstants.AddUpdateAttendenceList), HttpContext.Session.GetString(Constants.SessionBearerToken), true).Result.ToString();
                var result = JsonConvert.DeserializeObject<Result>(data);

                if (AttendenceListModel.ID > 0)
                {

                    return RedirectToAction("AttendenceListing");/*Constants.Index, WebControllarsConstants.AttendenceList, new { id = AttendenceListModel.ID.ToString() });*/

                }
                else
                {
                    return RedirectToActionPermanent(WebControllarsConstants.AttendenceListing, WebControllarsConstants.Attendance);

                }

            }
            else
            {
                return View(AttendenceListModel);
            }
        }

        [HttpGet]
        public IActionResult AttendenceList()
        {

            var EmployeeID = GetSessionInt(Constants.EmployeeID);
            var RoleId = GetSessionInt(Constants.RoleID);

            var FormPermission = _CheckUserFormPermission.GetFormPermission(EmployeeID, (int)PageName.AttendenceList);
            if (FormPermission.HasPermission == 0 && RoleId != (int)Roles.Admin && RoleId != (int)Roles.SuperAdmin)
            {
                HttpContext.Session.Clear();
                HttpContext.SignOutAsync();
                return RedirectToAction("Index", "Home", new { area = "" });
            }
            return View();
        }
        [HttpPost]
        public IActionResult AttendenceCalendarList(AttendanceInputParams objmodel)
        {
            var employeeId = Convert.ToInt64(HttpContext.Session.GetString(Constants.EmployeeID));
            var employeeName = Convert.ToString(HttpContext.Session.GetString(Constants.FirstName));
            var employeeMiddleName = Convert.ToString(HttpContext.Session.GetString(Constants.MiddleName));
            var employeeLastName = Convert.ToString(HttpContext.Session.GetString(Constants.Surname));
            var EmployeeNumber = Convert.ToString(HttpContext.Session.GetString(Constants.EmployeeNumberWithoutAbbr));
            
            var employeeFullName = string.Join(separator: " ", new[] { employeeName, employeeMiddleName, employeeLastName }.Where(name => !string.IsNullOrWhiteSpace(name)));
            ViewBag.employeeFullName = employeeFullName;
            

            AttendanceInputParams models = new AttendanceInputParams();
            models.Year = objmodel.Year;
            models.Month = objmodel.Month;
            models.UserId = Convert.ToInt64(EmployeeNumber);

            var data = _businessLayer.SendPostAPIRequest(models, _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.AttendenceList, APIApiActionConstants.GetAttendanceForMonthlyViewCalendar), HttpContext.Session.GetString(Constants.SessionBearerToken), true).Result.ToString();
            var model = JsonConvert.DeserializeObject<MonthlyViewAttendance>(data);
            return Json(new { data = model, employeeFullName = employeeFullName });
        }
        [HttpGet]
        public IActionResult MyAttendanceList()
        {

            var ManagerL1 = HttpContext.Session.GetString(Constants.Manager1Name).ToString();
            var ManagerL2 = HttpContext.Session.GetString(Constants.Manager2Name).ToString();
            ViewBag.ManagerL1 = ManagerL1;
            ViewBag.ManagerL2 = ManagerL2;
            return View();
        }
        [HttpPost]
        public JsonResult GetMyAttendenceList(string sEcho, int iDisplayStart, int iDisplayLength, string sSearch)
        {
            var ManagerL1 = HttpContext.Session.GetString(Constants.Manager1Name).ToString();
            var ManagerL2 = HttpContext.Session.GetString(Constants.Manager2Name).ToString();
            ViewBag.ManagerL1 = ManagerL1;
            ViewBag.ManagerL2 = ManagerL2;
            AttendanceInputParams attendenceListParams = new AttendanceInputParams();
            attendenceListParams.Month = DateTime.Now.Month;
            attendenceListParams.Year = DateTime.Now.Year;
            attendenceListParams.UserId = Convert.ToInt64(HttpContext.Session.GetString(Constants.EmployeeID));
            var data = _businessLayer.SendPostAPIRequest(attendenceListParams, _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.AttendenceList, APIApiActionConstants.GetMyAttendanceList), HttpContext.Session.GetString(Constants.SessionBearerToken), true).Result.ToString();

            var model = JsonConvert.DeserializeObject<MyAttendanceList>(data);
            model.Attendances.ForEach(x => x.EncodedId = _businessLayer.EncodeStringBase64(x.ID.ToString()));

            return Json(new { data = model });
        }
        [HttpGet]
        public IActionResult MyAttendance(string id)
        {
            Attendance model = new Attendance();
            if (!string.IsNullOrEmpty(id))
            {
                id = _businessLayer.DecodeStringBase64(id);
                model.ID = Convert.ToInt64(id);
                var data = _businessLayer.SendPostAPIRequest(model, _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.AttendenceList, APIApiActionConstants.GetAttendenceListID), HttpContext.Session.GetString(Constants.SessionBearerToken), true).Result.ToString();
                model = JsonConvert.DeserializeObject<HRMS.Models.Common.Results>(data).AttendanceModel;
            }
            //HRMS.Models.Common.Results results = GetAllEmployees(Convert.ToInt64(HttpContext.Session.GetString(Constants.EmployeeID)));

HRMS.Web/HRMS.Web/Areas/Employee/Views/Attendance/Index.cshtml
@using HRMS.Models.Common
@model Attendance
@{
    Layout = "~/Areas/Employee/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Attendance List";

}

<div class="main-header anim" style="--delay: 0s">Attendance List </div>
<form method="post" enctype="multipart/form-data">
    <div class="Container">
        <div class="group-box anim" style="--delay: .3s">

            @* <div class="col-md-12" style="background-color: #a7b5ce; padding: 5px;padding-left: 10px;">
            <label class="form-label">Attendence List</label>
            </div> *@
            @Html.HiddenFor(x => x.ID)
            <div class="row">
                <div class="col-md-4 form-group">
                    <label>Start Date <span class="Mandetory">*</span></label>

                    @Html.TextBoxFor(a => a.FirstLogDate, "{0:yyyy-MM-ddTHH:mm}", new { @class = "form-control", @type = "datetime-local", @required = "required" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 form-group">
                    <label>END Date <span class="Mandetory">*</span></label>
                    @Html.TextBoxFor(a => a.LastLogDate, "{0:yyyy-MM-ddTHH:mm}", new { @class = "form-control", @type = "datetime-local", @required = "required" })
                </div>
            </div>

           @*  <div class="row">
                <div class="col-md-4 form-group">
                    <label>Employee <span class="Mandetory">*</span></label>
                    @Html.DropDownListFor(x => x.UserId, Model.Employeelist, HRMS.Models.Common.Constants.SelectEmployee, new { @class = "form-control", @required = "required" })
                </div>
            </div>
 *@
            @*  <div class="row">
            <div class="col-md-4 form-group">
            <label>Status <span class="Mandetory">*</span></label>
            @Html.DropDownListFor(model => model.SelectedStatus, Model.StatusList, "-- Select Status --", new { @class = "form-control" })
            </div>
            </div> *@

            @*      <div class="row">
            <div class="col-md-4 form-group">
            <label>Shift Selection </label>
            @Html.DropDownListFor(model => model.SelectedShift, Model.ShiftList, " -- Select Shift --", new { @class = "form-control" })
            </div>
            </div> *@

            @* <div class="row">
            <div class="col-md-2 form-group">
            <label>Late Entry <span class="Mandetory">*</span></label><br />
            @Html.CheckBoxFor(a => a.LateEntry)
            </div>

            <div class="col-md-2 form-group">
            <label>Early Exit <span class="Mandetory">*</span></label><br />
            @Html.CheckBoxFor(a => a.EarlyExit)
            </div>
            </div>
            *@










            @* <div class="row">
            <div class="col-md-12">
            <input style="float:right" type="submit" value="Submit" class="btn btn-success" />
            <input id="cancelButton" style="float:right; margin:0 16px;" type="button" value="Cancel" class="btn btn-success" />
            </div>
            </div> *@
            <div class="row">
                <div class="col-md-12">
                    <input type="submit" value="Submit" class="btn btn-success" />
                    <button id="cancelButton" class="btn btn-danger" type="button" value="Cancel">Cancel</button>
                </div>
            </div>


        </div>
    </div>
</form>

HRMS.Web/HRMS.Web/Areas/Employee/Views/Attendance/MyAttendance.cshtml
@using HRMS.Models.Common

@using Microsoft.AspNetCore.Http
@using Microsoft.Extensions.Configuration
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@inject IConfiguration _configuration
@model Attendance
@{
    Layout = String.Format("~/Areas/{0}/Views/Shared/_Layout.cshtml", @HttpContextAccessor.HttpContext.Session.GetString(HRMS.Models.Common.Constants.AreaName));
    ViewData["Title"] = "Attendance List";

}
<div class="main-header anim" style="--delay: 0s">Add Attendance</div>
<form method="post" enctype="multipart/form-data">
    <div class="Container">
        <div class="group-box anim" style="--delay: .3s">

            <input type="hidden" name="ID" value="@Model.ID"/>
            @{
                var now = DateTime.Now;
                var threeDaysAgo = now.AddDays(-3);
            }

            <div class="row d-flex">
                <div class="col-md-6 form-group">
                    <label>Start Date <span class="Mandetory">*</span></label>
                    @Html.TextBoxFor(a => a.FirstLogDate, "{0:yyyy-MM-ddTHH:mm}", new
                        {
                            @class = "form-control",
                            @type = "datetime-local",
                            @required = "required",
                            min = threeDaysAgo.ToString("yyyy-MM-ddTHH:mm"),
                            max = now.ToString("yyyy-MM-ddTHH:mm")
                        })
                </div>
                <div class="col-md-6 form-group">
                    <label>End Date <span class="Mandetory">*</span></label>
                    @Html.TextBoxFor(a => a.LastLogDate, "{0:yyyy-MM-ddTHH:mm}", new
                        {
                            @class = "form-control",
                            @type = "datetime-local",
                            @required = "required",
                            min = threeDaysAgo.ToString("yyyy-MM-ddTHH:mm"),
                            max = now.ToString("yyyy-MM-ddTHH:mm")
                        })
                </div>
            </div>

            <div class="row">
                <div class="col-md-6 form-group">
                    <label>Comment <span class="Mandetory">*</span></label>
                    @Html.TextAreaFor(a => a.Comments, new
                        {
                            @class = "form-control",
                            @required = "required",
                            rows = "4", // You can adjust the rows as needed
                            cols = "50" // Optional, can be removed if not needed
                        })
                </div>

            </div>
            <div class="row d-flex text-end">
                <div class="col-md-12">
                    <input type="submit" value="Submit" class="btn btn-success" />
                    <a href="/employee/Attendance/MyAttendanceList" class="btn btn-danger" type="button" value="Cancel">Cancel</a>
                </div>
            </div>
        </div>
    </div>
</form>

HRMS.Web/HRMS.Web/Areas/Employee/Views/Attendance/TeamAttendenceApprovalList.cshtml
@using HRMS.Models.Common
<link href="~/assets/pages/gridlist.css" rel="stylesheet" />

@{
	Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
	ViewData["Title"] = "Attendance Approval List";
}
<div class="group-box anim">
    <div class="card shadow-sm border-0">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h6 class="mb-0">Attendance Approval List</h6>


            <div class="d-flex gap-2">
                <select id="ddlAttendanceStatus" class="form-select form-select-sm" style="width:150px;">
                    <option value="">Select Status</option>
                    <option value="1">Approve</option>
                    <option value="2">Reject</option>
                </select>

                <button id="btnUpdateSelected" class="btn btn-primary btn-sm">
                    Update Selected
                </button>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="card">
                <div class="card-body">

                    <table id="tblAttendanceApproval" class="table table-striped body-text" style="width:100%">
                        <thead>
                            <tr>
                                <th style="width:40px;"><input type="checkbox" id="selectAll" /></th>
                                <th style="display:none;">Employee ID</th>
                                <th>Emp No</th>
                                <th>Emp Name</th>
                                <th>Work Date</th>
                                <th>Status</th>
                                <th>Remarks</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
	</div>
    <script type="text/javascript">

	   $(document).ready(function ()
	   {
			var table = $('#tblAttendanceApproval').DataTable(
			{
				  processing: true,
				  serverSide: true,
				  ordering: true,
				  paging: true,
				  searching: true,
				ajax:{
				      url: '@Url.Action("GetAttendanceApprovalList", "Attendance", new { area = "Employee" })',
				      type: 'POST',
				      datatype: 'json',
				      data: function (d)
				      {
                          var sortColumn = typeof d.order[0] !== 'undefined' ? d.columns[d.order[0].column].data : 'employeNumber';
					    var sortDirection = typeof d.order[0] !== 'undefined' ? d.order[0].dir : 'asc';
					    return {
						        sEcho: d.draw,
						        iDisplayStart: d.start,
						        iDisplayLength: d.length,
						        sSearch: d.search.value,
						        sortCol: sortColumn,
						        sortDir: sortDirection
					    };
				      }
			    },
			   columns: [
                           {
                                data: "id",
                                 render: function (data) {
                                 return '<input type="checkbox" class="row-select" value="' + data + '">';
                                 }
                           },
                           { data: "employeeId", visible: false },
                           { data: "employeNumber" },
                           { data: "employeeName" },
                           {
                              data: "workDate",
						       render: function (data)
						       {
                                    if (data) {
                                            return new Date(data).toLocaleDateString();
                                           }
                                    return '';
                               }
                           },
                           { data: "attendanceStatus" },
                           { data: "remarks" }
			   ],
			   columnDefs: [
				         { "targets": [0], "orderable": false, },
				         { "targets": [1], "orderable": false, }
					],
					responsive: true,
                    order: []
		   });



		$('#selectAll').on('click', function () {
			$('.row-select').prop('checked', this.checked);
		});

		$('#btnUpdateSelected').on('click', function ()
	   {
			   const table = $('#tblAttendanceApproval').DataTable();
			   const selectedStatus = $('#ddlAttendanceStatus').val();
			   const selectedRecords = [];
			  const checkedRows = $('#tblAttendanceApproval .row-select:checked');


		 if (!selectedStatus)
		 {
		   toastEMessage('Error', 'Please select a status (Approved/Rejected)');
			  return;
		 }

		checkedRows.each(function ()
			{
			 const rowData = table.row($(this).closest('tr')).data();
				selectedRecords.push(
			{
				ID:rowData.id,
				EmployeeId: rowData.employeeId,
				WorkDate: rowData.workDate,
				AttendanceStatus: rowData.attendanceStatus,
				Remarks: rowData.remarks,
				ApprovedStatus: selectedStatus,
			});
		});

			if (selectedRecords.length === 0)
			{
			 toastEMessage('Error', 'Please select at least one attendance record');
			 return;
		    }


		const $button = $(this);
		$button.prop('disabled', true).html('<i class="fas fa-spinner fa-spin"></i> Processing...');

		$.ajax({
			type: "POST",
			url: '@Url.Action("SaveBulkAttendanceStatus", "Attendance", new { area = "Employee" })',
			contentType: "application/json",
			data: JSON.stringify(selectedRecords),
			success: function (response) {
				if (response.success) {
					toastMessage('Success', response.message);
					table.ajax.reload(null, false);
				} else {
					toastEMessage('Error', response.message || 'Failed to approve records');
				}
			},
			error: function (xhr) {
				const errorMsg = xhr.responseJSON?.message || 'Server error occurred';
				toastEMessage('Error', errorMsg);
			},
			complete: function ()
			{
				$button.prop('disabled', false).text('Approve Selected');
				$('#selectAll').prop('checked', false);
			}
		});
	});


	});

	function toastEMessage(type, message)
	{
		$.toast(
			{
					heading: 'Error',
					text: message,
					showHideTransition: 'slide',
					icon: 'error',
					position: 'top-right',
			});
	}

	function toastMessage(type , message)
		 {
			  $.toast(
				{
					heading: type,
					text: message,
					showHideTransition: 'slide',
					icon: 'success',
					position: 'top-right',
				});
		 }
    </script>