HRMS.Web/HRMS.Web/Areas/Admin/Controllers/PayrollController.cs
using Microsoft.AspNetCore.Mvc;
using HRMS.Web.BusinessLayer;
using Microsoft.AspNetCore.Authorization;
using HRMS.Models.Common;
using HRMS.Models.PayRoll;
using Newtonsoft.Json;
using OfficeOpenXml.FormulaParsing.Excel.Functions.Text;
using Microsoft.AspNetCore.Mvc.Razor;
namespace HRMS.Web.Areas.Admin.Controllers
{
    [Area(Constants.ManageAdmin)]
    [Authorize]
    public class PayrollController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IBusinessLayer _businessLayer;
        public PayrollController(IConfiguration configuration, IBusinessLayer businessLayer)
        {
            _configuration = configuration;
            _businessLayer = businessLayer;
        }

        public IActionResult MonthlySalary()
        {

            return View();
        }

        [HttpPost]
        public JsonResult MonthlySalary(string sEcho, int iDisplayStart, int iDisplayLength, string sSearch, string sortCol, string sortDir,
    int year,
    int month)
        {
            var companyId = Convert.ToInt64(HttpContext.Session.GetString(Constants.CompanyID));
            SalaryInputParams salaryInputParams = new SalaryInputParams
            {
                Month = month,
                Year = year,
                DisplayStart = iDisplayStart,
                DisplayLength = iDisplayLength,
                Searching = sSearch,
                SortCol = sortCol,
                SortDir = sortDir,
                CompanyID = companyId,
                EmployeeID = 0
            };
            var data = _businessLayer.SendPostAPIRequest(
                salaryInputParams,
                _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.Payroll, APIApiActionConstants.GetEmployeesMonthlySalary),
                HttpContext.Session.GetString(Constants.SessionBearerToken),
                true
            ).Result.ToString();
            var model = JsonConvert.DeserializeObject<List<SalaryDetails>>(data);
            if (model.Any())
            {
                model.ForEach(x => { x.EncryptedSalaryID = _businessLayer.EncodeStringBase64(x.MonthlySalaryID.ToString()); });

            }
            return Json(new
            {
                draw = sEcho,
                recordsTotal = model.Count,
                recordsFiltered = model.Count,
                data = model
            });
        }




        [HttpGet]
        public IActionResult SalaryDetails(string id)
        {
            if (string.IsNullOrEmpty(id))
                return RedirectToAction("MonthlySalary");
            var monthlySalaryID = Convert.ToInt64(_businessLayer.DecodeStringBase64(id));
            SalaryInputParams salaryInputParams = new SalaryInputParams
            {
                CompanyID = Convert.ToInt64(HttpContext.Session.GetString(Constants.CompanyID)),
                MonthlySalaryID = monthlySalaryID,
                EmployeeID = Convert.ToInt64(HttpContext.Session.GetString(Constants.EmployeeID)),
                Year = 0,
                Month = 0,
                Searching = null,
                DisplayStart = 0,
                DisplayLength = 1,
                SortCol = null,
                SortDir = null
            };

            var salaryDetailsJson = _businessLayer.SendPostAPIRequest(
                salaryInputParams,
                _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.Payroll, APIApiActionConstants.GetEmployeesMonthlySalary),
                HttpContext.Session.GetString(Constants.SessionBearerToken),
                true
            ).Result.ToString();

            if (string.IsNullOrEmpty(salaryDetailsJson))
                return NotFound();
            var salaryDetails = JsonConvert.DeserializeObject<List<SalaryDetails>>(salaryDetailsJson)?.FirstOrDefault();
            if (salaryDetails == null)
                return NotFound();

            return View(salaryDetails);
        }


        public IActionResult EditSalary(string id)
        {
            if (string.IsNullOrEmpty(id))
                return RedirectToAction("MonthlySalary");
            var monthlySalaryID = Convert.ToInt64(_businessLayer.DecodeStringBase64(id));
            SalaryInputParams salaryInputParams = new SalaryInputParams
            {
                CompanyID = Convert.ToInt64(HttpContext.Session.GetString(Constants.CompanyID)),
                MonthlySalaryID = monthlySalaryID,
                EmployeeID = Convert.ToInt64(HttpContext.Session.GetString(Constants.EmployeeID)),
                Year = 0,
                Month = 0,
                Searching = null,
                DisplayStart = 0,
                DisplayLength = 1,
                SortCol = null,
                SortDir = null
            };
            // Call API to get salary details
            var salaryDetailsJson = _businessLayer.SendPostAPIRequest(

                    salaryInputParams,
                _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.Payroll, APIApiActionConstants.GetEmployeesMonthlySalary),
                HttpContext.Session.GetString(Constants.SessionBearerToken),
                true
            ).Result?.ToString();

            if (string.IsNullOrEmpty(salaryDetailsJson))
                return NotFound();

            // Deserialize as a list but pick the first record
            var salaryDetails = JsonConvert.DeserializeObject<List<EmployeeMonthlySalaryModel>>(salaryDetailsJson)?.FirstOrDefault();

            if (salaryDetails == null)
                return NotFound();

            // Set UpdatedByUserID from session
            salaryDetails.UpdatedByUserID = Convert.ToInt64(HttpContext.Session.GetString(Constants.EmployeeID));
            return View(salaryDetails);
        }


        [HttpPost]
        public IActionResult EditSalary(EmployeeMonthlySalaryModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            model.UpdatedByUserID = Convert.ToInt64(HttpContext.Session.GetString(Constants.EmployeeID));

            var apiResponse = _businessLayer.SendPostAPIRequest(
                model,
                _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.Payroll, APIApiActionConstants.AddUpdateEmployeeMonthlySalary),
                HttpContext.Session.GetString(Constants.SessionBearerToken),
                true
            ).Result;
            var result = JsonConvert.DeserializeObject<Result>(apiResponse?.ToString() ?? "{}");
            if (result != null && !string.IsNullOrEmpty(result.Message) &&
                result.Message.Contains("success", StringComparison.OrdinalIgnoreCase))
            {
                TempData[HRMS.Models.Common.Constants.toastType] = HRMS.Models.Common.Constants.toastTypeSuccess;
                TempData[HRMS.Models.Common.Constants.toastMessage] = result.Message;
                return RedirectToAction("MonthlySalary");
            }
            else
            {
                TempData[HRMS.Models.Common.Constants.toastType] = HRMS.Models.Common.Constants.toastTypeError;
                TempData[HRMS.Models.Common.Constants.toastMessage] = result?.Message ?? "Failed to update salary.";
                return View(model);
            }
        }


      

    }
}

HRMS.Web/HRMS.Web/Areas/Admin/Views/Payroll/EditSalary.cshtml
@using HRMS.Models.PayRoll
@model EmployeeMonthlySalaryModel

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Edit Salary";
   
}


<div class="main-header anim">

    <div class="header-left">
        Edit Salary -  @Model.EmployeeName (@Model.EmployeeNumber)
    </div>

</div>
    



<form asp-action="EditSalary" method="post">

    @Html.HiddenFor(m => m.MonthlySalaryID)
    @Html.HiddenFor(m => m.UpdatedByUserID)

    <div class="row group-box anim">

        <div class="col-md-3">
            <label>Gross Salary</label>
            @Html.TextBoxFor(m => m.GrossSalary, new
            {
                @class = "form-control",
                type = "number",
                step = "0.01",
                min = "0",      
                
            })
        </div>
        <div class="col-md-3">
            <label>Payroll Type</label>
            @Html.TextBoxFor(m => m.PayrollTypeName, new { @class = "form-control", type = "text", id = "PayrollTypeName", @readonly = "readonly" })
        </div>
        <div class="col-md-3">
            <label>Basic Salary</label>
            @Html.TextBoxFor(m => m.BasicSalary, new { @class = "form-control", type = "number", step = "0.01", @readonly = "readonly" })
        </div>
        <div class="col-md-3">
            <label>HRA</label>
            @Html.TextBoxFor(m => m.HRA, new { @class = "form-control", type = "number", step = "0.01", @readonly = "readonly" })
        </div>
        <div class="col-md-3">
            <label>Conveyance Allowance</label>
            @Html.TextBoxFor(m => m.ConveyanceAllowance, new { @class = "form-control", type = "number", step = "0.01", @readonly = "readonly" })
        </div>

        <div class="col-md-3">
            <label>Special Allowance</label>
            @Html.TextBoxFor(m => m.SpecialAllowance, new { @class = "form-control", type = "number", step = "0.01", @readonly = "readonly" })
        </div>
        <div class="col-md-3">
            <label>PF</label>
            @Html.TextBoxFor(m => m.PF, new { @class = "form-control", type = "number", step = "0.01", @readonly = "readonly" })
        </div>
        <div class="col-md-3">
            <label>ESI</label>
            @Html.TextBoxFor(m => m.ESI, new { @class = "form-control", type = "number", step = "0.01", @readonly = "readonly" })
        </div>
        <div class="col-md-3">
            <label>LWF</label>
            @Html.TextBoxFor(m => m.LWF, new { @class = "form-control", type = "number", step = "0.01", @readonly = "readonly" })
        </div>

        <div class="col-md-3">
            <label>PTax</label>
            @Html.TextBoxFor(m => m.PTax, new { @class = "form-control", type = "number", step = "0.01", @readonly = "readonly" })
        </div>
        <div class="col-md-3">
            <label>TDS</label>
            @Html.TextBoxFor(m => m.TDS, new { @class = "form-control", type = "number", step = "0.01", @readonly = "readonly" })
        </div>

        <div class="col-md-3">
            <label>Employer PF</label>
            @Html.TextBoxFor(m => m.EmployerPF, new { @class = "form-control", type = "number", step = "0.01", @readonly = "readonly" })
        </div>
        <div class="col-md-3">
            <label>Employer ESI</label>
            @Html.TextBoxFor(m => m.EmployerESI, new { @class = "form-control", type = "number", step = "0.01", @readonly = "readonly" })
        </div>
        <div class="col-md-3">
            <label>Employer LWF</label>
            @Html.TextBoxFor(m => m.EmployerLWF, new { @class = "form-control", type = "number", step = "0.01", @readonly = "readonly" })
        </div>

        <div class="col-md-3">
            <label>Gratuity</label>
            @Html.TextBoxFor(m => m.Gratuity, new { @class = "form-control", type = "number", step = "0.01", @readonly = "readonly" })
        </div>
        <div class="col-md-3">
            <label>Total Earnings</label>
            @Html.TextBoxFor(m => m.TotalEarnings, new { @class = "form-control", type = "number", step = "0.01", @readonly = "readonly" })
        </div>
        <div class="col-md-3">
            <label>Total Deductions</label>
            @Html.TextBoxFor(m => m.TotalDeductions, new { @class = "form-control", type = "number", step = "0.01", @readonly = "readonly" })
        </div>
        <div class="col-md-3">
            <label>In Hand Salary</label>
            @Html.TextBoxFor(m => m.InHandSalary, new { @class = "form-control", type = "number", step = "0.01", @readonly = "readonly" })
        </div>
        <div class="col-md-3">
            <label>Cost To Company</label>
            @Html.TextBoxFor(m => m.CostToCompany, new { @class = "form-control", type = "number", step = "0.01", @readonly = "readonly" })
        </div>

        <div class="col-md-6">
                <label>Status</label>
                @Html.TextBoxFor(m => m.Status, new { @class = "form-control" })
            </div>
        <div class="col-md-6">
            <label>Remarks</label>
            @Html.TextAreaFor(m => m.Remarks, new { @class = "form-control", rows = 2 })
        </div>

        <div class="col-md-12 mt-3">
            <button type="submit" class="btn btn-success">Save</button>
            <a asp-action="MonthlySalary" class="btn btn-danger">Cancel</a>
        </div>
    </div>
</form>
@section Scripts{
    <script>
$(document).ready(function(){

    function calculateSalary() {
        var gross = parseFloat($('#GrossSalary').val()) || 0;
        var type = $('#PayrollTypeName').val();

        var basic = 0, hra = 0, conveyance = 0, special = 0;
        var pf = 0, esi = 0, lwf = 0, ptax = 0, tds = 0;
        var employerPF = 0, employerESI = 0, employerLWF = 0, gratuity = 0;
        var totalEarnings = 0, totalDeductions = 0, inHand = 0, ctc = 0;

        if(!type){
            alert('Invalid Payroll Type');
            return;
        }


        if(type === 'NAPS' || type === 'NATS'){
            basic = gross;
        }
     
        else if(type === 'OJT'){
            basic = gross;
            esi = (gross <= 21000) ? Math.ceil(gross * 0.0075) : 0;
            employerESI = (gross <= 21000) ? Math.ceil(gross * 0.0325) : 0;
        }

        else if(type === 'Regular'){
            basic = Math.round(gross * 0.50);
            hra = Math.round(gross * 0.25);
            conveyance = Math.round(gross * 0.10);
            special = gross - (basic + hra + conveyance);

            pf = (gross <= 15000) ? Math.round(gross * 0.12) : Math.round(15000 * 0.12);
            esi = ((gross - conveyance) <= 21000) ? Math.ceil((gross - conveyance) * 0.0075) : 0;
            lwf = 5;
            ptax = (gross > 25000) ? 200 : 0;
            tds = 0;

            employerPF = (gross <= 15000) ? Math.round(gross * 0.13) : Math.round(15000 * 0.13);
            employerESI = ((gross - conveyance) <= 21000) ? Math.ceil((gross - conveyance) * 0.0325) : 0;
            employerLWF = 20;
        }

        gratuity = 0;
        totalEarnings = gross;
        totalDeductions = pf + esi + lwf + ptax + tds;
        inHand = totalEarnings - totalDeductions;
        ctc = gross + employerPF + employerESI + employerLWF + gratuity;

        // Set values to inputs
        $('#BasicSalary').val(basic);
        $('#HRA').val(hra);
        $('#ConveyanceAllowance').val(conveyance);
        $('#SpecialAllowance').val(special);

        $('#PF').val(pf);
        $('#ESI').val(esi);
        $('#LWF').val(lwf);
        $('#PTax').val(ptax);
        $('#TDS').val(tds);

        $('#EmployerPF').val(employerPF);
        $('#EmployerESI').val(employerESI);
        $('#EmployerLWF').val(employerLWF);
        $('#Gratuity').val(gratuity);

        $('#TotalEarnings').val(totalEarnings);
        $('#TotalDeductions').val(totalDeductions);
        $('#InHandSalary').val(inHand);
        $('#CostToCompany').val(ctc);
    }


    $('#GrossSalary, #PayrollTypeName').on('input change', calculateSalary);

  
    calculateSalary();
});
    </script>
}

HRMS.Web/HRMS.Web/Areas/Admin/Views/Payroll/MonthlySalary.cshtml
@using HRMS.Models.PayRoll
<link href="~/assets/pages/gridlist.css" rel="stylesheet" />

 @model List<HRMS.Models.PayRoll.SalaryDetails>
    @{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Monthly Salary";

    var success = TempData["Success"];
    var Err = TempData["Error"];
    }

    <div class="main-header anim" style="--delay: 0s">
        Monthly Salary List
    </div>
    <div class="table-responsive py-3">
        <div class="row mb-3">
            <div class="col-md-2">
                <label for="yearDropdown">Year</label>
                <div class="custom-select-wrapper">
                    <select class="form-select custom-select" id="yearDropdown"></select>
                </div>
            </div>
            <div class="col-md-2">
                <label for="monthDropdown">Month</label>
                <div class="custom-select-wrapper">
                    <select class="form-select custom-select" id="monthDropdown"></select>
                </div>
            </div>
        </div>
        <table id="tblMonthlySalary" class="table table-striped body-text" style="width:100%">
            <thead>
                <tr>
                    <th style="display:none"></th>
                    <th>Employee Number</th>
                    <th>Employee Name</th>
                    <th>Gross Salary</th>
                    <th>Basic Salary</th>
                    <th>HRA</th>
                    <th>Conveyance Allowance</th>
                    <th>Special Allowance</th>
                    <th>In-Hand Salary</th>
                    <th>Cost To Company</th>
                    <th>Action</th>
                </tr>
            </thead>
        </table>
    </div>
    <script type="text/javascript">

      $(document).ready(function () {


    populateYearDropdown();
    populateMonthDropdown();
    initializeDataTable();
    registerDropdownChange();

    
    function populateYearDropdown() {
        var currentYear = new Date().getFullYear();
        var startYear = currentYear - 5; 
        var endYear = currentYear + 1;

        var yearDropdown = $('#yearDropdown');
        yearDropdown.empty();
        yearDropdown.append('<option value="">Select Year</option>');

        for (var y = endYear; y >= startYear; y--) {
            yearDropdown.append(new Option(y, y));
        }

        yearDropdown.val(currentYear); 
    }


    function populateMonthDropdown() {
        var months = [
            "January", "February", "March", "April", "May", "June",
            "July", "August", "September", "October", "November", "December"
        ];

        var currentMonth = new Date().getMonth() + 1; 
        var monthDropdown = $('#monthDropdown');
        monthDropdown.empty();
        monthDropdown.append('<option value="">Select Month</option>');

        for (var m = 1; m <= 12; m++) {
            monthDropdown.append(new Option(months[m - 1], m));
        }

        monthDropdown.val(currentMonth); 
    }

  
    function initializeDataTable() {
        $('#tblMonthlySalary').DataTable({
            processing: true,
            serverSide: true,
            destroy: true, 
            ajax: {
                url: '@Url.Action("MonthlySalary", "Payroll")',
                type: 'POST',
                datatype: 'json',
                data: function (d) {
                    var sortColumn = d.order?.length ? d.columns[d.order[0].column].data : 'EmployeeID';
                    var sortDirection = d.order?.length ? d.order[0].dir : 'asc';
                    return {
                        sEcho: d.draw,
                        iDisplayStart: d.start,
                        iDisplayLength: d.length,
                        sSearch: d.search.value,
                        sortCol: sortColumn,
                        sortDir: sortDirection,
                        year: $('#yearDropdown').val(),
                        month: $('#monthDropdown').val()
                    };
                }
            },
            columns: [
                { data: "encryptedSalaryID", visible: false },
                { data: "employeeNumber" },
                { data: "employeeName" },                
                { data: "grossSalary" },
                { data: "basicSalary" },
                { data: "hra" },
                { data: "conveyanceAllowance" },
                { data: "specialAllowance" },
                { data: "inHandSalary" },
                { data: "costToCompany" },
                {
                    render: function (data, type, row) {
                        return `<a class="item" href="/admin/Payroll/SalaryDetails?id=${row.encryptedSalaryID}" data-bs-toggle="tooltip" title="View Salary" style="margin-right:8px;">
                                     <i class="bi bi-eye-fill" style="font-size:18px; color:#044a8c;"></i>
                                </a>
                                <a class="item text-success" href="/admin/Payroll/EditSalary?id=${row.encryptedSalaryID}" data-bs-toggle="tooltip" title="Edit Salary">
                <i class="bi bi-pencil-fill" style="font-size:18px; "></i>
            </a>`;
                    }
                }
            ],
            responsive: true
        });
    }

    function registerDropdownChange() {
        $('#yearDropdown, #monthDropdown').change(function () {
            $('#tblMonthlySalary').DataTable().ajax.reload();
        });
    }

});
    </script>
   

HRMS.Web/HRMS.Web/Areas/Admin/Views/Payroll/SalaryDetails.cshtml
@using HRMS.Models.PayRoll

@model SalaryDetails

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Salary Details";
   
}

<div class="main-header anim" style="--delay: 0s">
    Salary Details
</div>

<div class="Container">
    <div class="group-box anim" style="--delay: .3s">
        <div class="small-header">
            Employee Salary Slip
        </div>

        <div class="row mb-3">
            <div class="col-md-6">
                <strong>Employee Name:</strong> @Model.EmployeeName
            </div>
            <div class="col-md-6">
                <strong>Employee Number:</strong> @Model.EmployeeNumber
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-6">
                <strong>Salary Month/Year:</strong> @Model.SalaryMonth / @Model.SalaryYear
            </div>
            <div class="col-md-6">
                <strong>Payroll Type:</strong> @Model.PayrollTypeName
               
            </div>
        </div>

        <table class="table table-bordered table-striped">
            <thead style="background-color:#044a8c; color:white;">
                <tr>
                    <th>Earnings</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr><td>Gross Salary</td><td>@Model.GrossSalary</td></tr>
                <tr><td>Basic Salary</td><td>@Model.BasicSalary</td></tr>
                <tr><td>HRA</td><td>@Model.HRA</td></tr>
                <tr><td>Conveyance Allowance</td><td>@Model.ConveyanceAllowance</td></tr>
                <tr><td>Special Allowance</td><td>@Model.SpecialAllowance</td></tr>
                <tr><td>Total Earnings</td><td>@Model.TotalEarnings</td></tr>
            </tbody>
        </table>

        <table class="table table-bordered table-striped mt-3">
            <thead style="background-color:#044a8c; color:white;">
                <tr>
                    <th>Deductions</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr><td>PF</td><td>@Model.PF</td></tr>
                <tr><td>ESI</td><td>@Model.ESI</td></tr>
                <tr><td>LWF</td><td>@Model.LWF</td></tr>
                <tr><td>Professional Tax</td><td>@Model.PTax</td></tr>
                <tr><td>TDS</td><td>@Model.TDS</td></tr>
                <tr><td>Total Deductions</td><td>@Model.TotalDeductions</td></tr>
            </tbody>
        </table>

        <div class="row mt-3">
            <div class="col-md-6">
                <strong>In-Hand Salary:</strong> <span class="text-success">@Model.InHandSalary</span>
            </div>
            <div class="col-md-6">
                <strong>Cost To Company:</strong> @Model.CostToCompany
            </div>
        </div>

        <div class="row mt-4">
            <div class="col-md-12 text-end">
                <a href="@Url.Action("MonthlySalary", "Payroll" )" class="btn btn-secondary">Back</a>
            </div>
        </div>
    </div>
</div>