HRMS.Web/HRMS.Web/Areas/Admin/Controllers/LeavePolicyController.cs
using DocumentFormat.OpenXml.EMMA;
using HRMS.Models;
using HRMS.Models.Common;
using HRMS.Models.Employee;
using HRMS.Models.Leave;
using HRMS.Models.LeavePolicy;
using HRMS.Models.WhatsHappeningModel;
using HRMS.Web.BusinessLayer;
using HRMS.Web.BusinessLayer.S3;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Results = HRMS.Models.Common.Results;

namespace HRMS.Web.Areas.Admin.Controllers
{
    [Area(Constants.ManageAdmin)]
    [Authorize]
    public class LeavePolicyController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IS3Service _s3Service;
        private readonly IBusinessLayer _businessLayer;
        private Microsoft.AspNetCore.Hosting.IHostingEnvironment Environment;
        private readonly ICheckUserFormPermission _CheckUserFormPermission;
        public LeavePolicyController(ICheckUserFormPermission CheckUserFormPermission , IConfiguration configuration, IBusinessLayer businessLayer, Microsoft.AspNetCore.Hosting.IHostingEnvironment environment, IS3Service s3Service)
        {
            _configuration = configuration;
            _businessLayer = businessLayer;
            Environment = environment;
            _s3Service = s3Service;
            _CheckUserFormPermission = CheckUserFormPermission;
        }
        private int GetSessionInt(string key)
        {
            return int.TryParse(HttpContext.Session.GetString(key), out var value) ? value : 0;
        }
        public IActionResult LeavePolicyListing()
        {
            Results results = new Results();
            var EmployeeID = GetSessionInt(Constants.EmployeeID);
            var RoleId = GetSessionInt(Constants.RoleID);

            var FormPermission = _CheckUserFormPermission.GetFormPermission(EmployeeID, (int)PageName.LeavePolicyListing);
            if (FormPermission.HasPermission == 0 && RoleId != (int)Roles.Admin && RoleId != (int)Roles.SuperAdmin)
            {
                HttpContext.Session.Clear();
                HttpContext.SignOutAsync();
                return RedirectToAction("Index", "Home", new { area = "" });
            }
            return View(results);
        }

        [HttpPost]
        [AllowAnonymous]
        public JsonResult LeavePolicyListings(string sEcho, int iDisplayStart, int iDisplayLength, string sSearch)
        {
            LeavePolicyInputParans leavePolicyParams = new LeavePolicyInputParans();
            leavePolicyParams.CompanyID = Convert.ToInt64(HttpContext.Session.GetString(Constants.CompanyID));
            var data = _businessLayer.SendPostAPIRequest(leavePolicyParams, _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.LeavePolicy, APIApiActionConstants.GetAllLeavePolicies), HttpContext.Session.GetString(Constants.SessionBearerToken), true).Result.ToString();
            var results = JsonConvert.DeserializeObject<Results>(data);
            results.LeavePolicy.ForEach(x => x.EncodedId = _businessLayer.EncodeStringBase64(x.LeavePolicyID.ToString()));
            return Json(new { data = results.LeavePolicy });

        }

        public IActionResult Index(string id)
        {
            LeavePolicyModel leavePolicyModel = new LeavePolicyModel();
            leavePolicyModel.CompanyID = Convert.ToInt64(HttpContext.Session.GetString(Constants.CompanyID));                 
            if (!string.IsNullOrEmpty(id))
            {
                id = _businessLayer.DecodeStringBase64(id);
                leavePolicyModel.LeavePolicyID = Convert.ToInt64(id);
                var data = _businessLayer.SendPostAPIRequest(leavePolicyModel, _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.LeavePolicy, APIApiActionConstants.GetAllLeavePolicies), HttpContext.Session.GetString(Constants.SessionBearerToken), true).Result.ToString();
                leavePolicyModel = JsonConvert.DeserializeObject<Results>(data).leavePolicyModel;
            }

            return View(leavePolicyModel);
        }

        [HttpPost]
        public IActionResult Index(LeavePolicyModel leavePolicyModel)
        {
            //// Leaves less than maximum leaves
            //if (leavePolicyModel.MaximumEarnedLeaveAllowed + leavePolicyModel.MaximumMedicalLeaveAllocationAllowed + leavePolicyModel.MaximumCompOffLeaveAllocationAllowed > leavePolicyModel.MaximumLeaveAllocationAllowed)
            //{
            //    TempData[HRMS.Models.Common.Constants.toastType] = HRMS.Models.Common.Constants.toastTypeError;
            //    TempData[HRMS.Models.Common.Constants.toastMessage] = "The Casual,Medical and Annual leaves must be equal or less than to Maximum leaves allowed.";
            //    return View();
            //}
             
                leavePolicyModel.CompanyID = Convert.ToInt64(HttpContext.Session.GetString(Constants.CompanyID));

                var data = _businessLayer.SendPostAPIRequest(leavePolicyModel, _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.LeavePolicy, APIApiActionConstants.AddUpdateLeavePolicy), HttpContext.Session.GetString(Constants.SessionBearerToken), true).Result.ToString();
                var result = JsonConvert.DeserializeObject<Result>(data);

            TempData[HRMS.Models.Common.Constants.toastType] = HRMS.Models.Common.Constants.toastTypeSuccess;
                TempData[HRMS.Models.Common.Constants.toastMessage] = "Leave Policy created successfully.";
                return RedirectToActionPermanent(WebControllarsConstants.LeavePolicyListing, WebControllarsConstants.LeavePolicy);
             
        }
         


        #region Leave Policy Details

        public IActionResult LeavePolicyDetailsListing()
        {
            Results results = new Results();
            var EmployeeID = GetSessionInt(Constants.EmployeeID);
            var RoleId = GetSessionInt(Constants.RoleID);

            var FormPermission = _CheckUserFormPermission.GetFormPermission(EmployeeID, (int)PageName.LeavePolicyDetailsListing);
            if (FormPermission.HasPermission == 0 && RoleId != (int)Roles.Admin && RoleId != (int)Roles.SuperAdmin)
            {
                HttpContext.Session.Clear();
                HttpContext.SignOutAsync();
                return RedirectToAction("Index", "Home", new { area = "" });
            }
            return View(results);
        }

        [HttpPost]
        [AllowAnonymous]
        public JsonResult LeavePolicyDetailsListings(string sEcho, int iDisplayStart, int iDisplayLength, string sSearch)
        {
            LeavePolicyInputParans leavePolicyParams = new LeavePolicyInputParans();
            leavePolicyParams.CompanyID = Convert.ToInt64(HttpContext.Session.GetString(Constants.CompanyID));
            var data = _businessLayer.SendPostAPIRequest(leavePolicyParams, _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.LeavePolicy, APIApiActionConstants.GetLeavePolicyList), HttpContext.Session.GetString(Constants.SessionBearerToken), true).Result.ToString();
            var results = JsonConvert.DeserializeObject<Results>(data);
            results.LeavePolicyDetailsList.ForEach(x => x.EncodedId = _businessLayer.EncodeStringBase64(x.Id.ToString()));

            return Json(new { data = results.LeavePolicyDetailsList });

        }

        public IActionResult LeavePolicyDetails(string id)
        {
            LeavePolicyDetailsModel leavePolicyModel = new LeavePolicyDetailsModel();
            leavePolicyModel.CompanyID = Convert.ToInt64(HttpContext.Session.GetString(Constants.CompanyID));


            if (!string.IsNullOrEmpty(id))
            {

                id = _businessLayer.DecodeStringBase64(id);
                leavePolicyModel.Id = Convert.ToInt64(id);
                var data = _businessLayer.SendPostAPIRequest(leavePolicyModel, _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.LeavePolicy, APIApiActionConstants.GetAllLeavePolicyDetails), HttpContext.Session.GetString(Constants.SessionBearerToken), true).Result.ToString();
                leavePolicyModel = JsonConvert.DeserializeObject<Results>(data).LeavePolicyDetailsModel;
                if (!string.IsNullOrEmpty(leavePolicyModel.PolicyDocument))
                {
                    leavePolicyModel.PolicyDocument = _s3Service.GetFileUrl(leavePolicyModel.PolicyDocument);
                }
            }
            EmployeeInputParams employee = new EmployeeInputParams();
            employee.CompanyID = leavePolicyModel.CompanyID;
            var compay = _businessLayer.SendPostAPIRequest(employee, _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.Company, APIApiActionConstants.GetAllCompaniesList), HttpContext.Session.GetString(Constants.SessionBearerToken), true).Result.ToString();
            var results = JsonConvert.DeserializeObject<HRMS.Models.Common.Results>(compay);
            leavePolicyModel.Companies = results.Companies;


            LeavePolicyInputParans PolicyParams = new LeavePolicyInputParans();
            PolicyParams.CompanyID = Convert.ToInt64(HttpContext.Session.GetString(Constants.CompanyID));

            var Policy = _businessLayer.SendPostAPIRequest(PolicyParams, _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.Employee, APIApiActionConstants.GetPolicyCategoryList), HttpContext.Session.GetString(Constants.SessionBearerToken), true).Result.ToString();
            var Policyresults = JsonConvert.DeserializeObject<Results>(Policy);
            leavePolicyModel.PolicyList = Policyresults.PolicyCategoryList;


            return View(leavePolicyModel);
        }

        [HttpPost]
        public IActionResult LeavePolicyDetails(LeavePolicyDetailsModel leavePolicyModel, List<IFormFile> postedFiles)
        {
            string s3uploadUrl = _configuration["AWS:S3UploadUrl"];
          
            if(leavePolicyModel.Description==null)
            {
                leavePolicyModel.Description = string.Empty;

HRMS.Web/HRMS.Web/Areas/Admin/Views/LeavePolicy/AddWhatshappening.cshtml
@using HRMS.Models
@using HRMS.Models.Common
@using HRMS.Models.WhatsHappeningModel
@model WhatsHappeningModels
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Add WhatsHappening";
    var IconImage = !string.IsNullOrEmpty(Model.IconImage)
         ? Model.IconImage
         : HRMS.Models.Common.Constants.NoImagePath;

    var isEditMode = Model.WhatsHappeningID > 0;
}

<div class="main-header anim" style="--delay: 0s">
    What's Happening
</div>
<form id="AddWhatshappeningForm" method="post" enctype="multipart/form-data">

    <div class="Container">
        @Html.HiddenFor(x=>x.IconImage)
        @Html.HiddenFor(x=>x.WhatsHappeningID)
        <div class="group-box anim" style="--delay: .3s">
            <div class="row">
                <div class="col-md-6 form-group">
                    <label>Title <span class="Mandetory">*</span></label>
                    @Html.TextBoxFor(a => a.Title, new { @class = "form-control", @required = "required" })
                </div>

                
                <div class="col-md-3 form-group">
                    <label>FromDate <span class="Mandetory">*</span></label>
                    @Html.TextBoxFor(a => a.FromDate, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date", @required = "required" })
                </div>
                
                
                <div class="col-md-3 form-group">
                    <label>ToDate <span class="Mandetory">*</span></label>
                    @Html.TextBoxFor(a => a.ToDate, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date", @required = "required" })

                </div>


                <div class="col-md-12 form-group">
                    <label>Description <span class="Mandetory">*</span></label>
                    @Html.TextAreaFor(a => a.Description, new { @class = "form-control", id = "editor", rows = "10", cols = "50" })

                </div>
                <div class="col-md-4 form-group">
                    <label>Image <span class="Mandetory">*</span></label>
                    <div class="col-md-4">
                        <img id="previewImage" src="@IconImage"
                             onerror="this.onerror=null; this.src='@(HRMS.Models.Common.Constants.NoImagePath)'"
                             style="width:100px; height:100px" />
                    </div>
                    <div class="col-md-8">
                        <input type="file" name="postedFiles" accept="image/*" onchange="showPreview(event)"  @(isEditMode ? "" : "required") />
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <input type="submit" value="Submit" class="btn btn-success" />
                <input id="cancelButton" type="button" value="Cancel" class="btn btn-danger" />
            </div>
            <div class="col-md-2">

            </div>
           
        </div>
    </div>
</form>


<script>
    document.getElementById('cancelButton').addEventListener('click', function () {
        window.location.href = '@Url.Action("WhatshappeningListing", "LeavePolicy")';
    });

    ClassicEditor
        .create(document.querySelector('#editor'), {
            toolbar: [
                'heading', '|', 'bold', 'italic', 'link', 'bulletedList',
                'numberedList', 'blockQuote', '|', 'alignment', '|', 'undo', 'redo'
            ],
            alignment: {
                options: ['left', 'center', 'right', 'justify']
            },
            heading: {
                options: [
                    { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
                    { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
                    { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },
                    { model: 'heading3', view: 'h3', title: 'Heading 3', class: 'ck-heading_heading3' }
                ]
            }
        })
        .then(editor => {
            console.log('Editor was initialized', editor);
        })
        .catch(error => {
            console.error(error);
        });
       function showPreview(event) {
        const file = event.target.files[0];
        const maxSizeInMB = 4;
        if (file) {
            const maxSizeInBytes = maxSizeInMB * 1024 * 1024;        
            if (!file.type.startsWith('image/')) {
                alert("Only image files are allowed.");
                event.target.value = "";
                return; 
            }          
            if (file.size > maxSizeInBytes) {
                alert("Image size should not exceed 4MB.");
                event.target.value = "";
                return;
            }         
            const reader = new FileReader();
            reader.onload = function (e) {
                document.getElementById('previewImage').src = e.target.result;
            };
            reader.readAsDataURL(file);
        }
    }
</script>

HRMS.Web/HRMS.Web/Areas/Admin/Views/LeavePolicy/Index.cshtml
@using HRMS.Models.Common
@using HRMS.Models.LeavePolicy;
@model LeavePolicyModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Leave Policy";
}

<div class="main-header anim" style="--delay: 0s">Leave Policy Details </div>
<form id="leaveForm" method="post" enctype="multipart/form-data">

    <div class="Container">

        @*   Annual Leave *@
        <div class="group-box anim" style="--delay: .3s">
            <div class="row">
                <div class="col-md-4 form-group">
                    <label>Leave Policy Name <span class="Mandetory">*</span></label>
                    @Html.HiddenFor(x => x.LeavePolicyID)
                    @Html.TextBoxFor(a => a.LeavePolicyName, new { @class = "form-control", @required = "required" })
                </div>
            </div>
            <hr />
            <h3>Annual Leave</h3>
            <div class="row">
                <div class="col-md-4 form-group">
                    <label>Maximum Annual Leave Allocation Allowed <span class="Mandetory">*</span></label>
                    @Html.TextBoxFor(a => a.Annual_MaximumLeaveAllocationAllowed, new { @class = "form-control", @required = "required" })
                </div>
                <div class="col-md-4 form-group">
                    <label>Applicable After Working Days <span class="Mandetory">*</span></label>
                    @Html.TextBoxFor(a => a.Annual_ApplicableAfterWorkingDays, new { @class = "form-control", @required = "required" })
                </div>
                <div class="col-md-4 form-group">
                    <label>Maximum Consecutive Leaves Allowed</label>
                    @Html.TextBoxFor(a => a.Annual_MaximumConsecutiveLeavesAllowed, new { @class = "form-control" })
                </div>
                <div class="col-md-4 form-group">
                    <label>Maximum Medical Leaves Allocation Allowed <span class="Mandetory">*</span></label>
                    @Html.TextBoxFor(a => a.Annual_MaximumMedicalLeaveAllocationAllowed, new { @class = "form-control", @id = "medicalLeaveInput" })
                </div>
                 <div class="col-md-4 form-group" id="documentRequiredField" style="display:none;">
                    <label> Medical Document Required <span class="Mandetory">*</span></label><br />
                    @Html.CheckBoxFor(a => a.Annual_MedicalDocument)
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 form-group">
                    <label>Is Carry Forward <span class="Mandetory">*</span></label><br />
                    @Html.CheckBoxFor(a => a.Annual_IsCarryForward, new { id = "carryForwardCheckbox" })
                </div>
                    <div class="col-md-4 form-group" id="earnedLeaveAllocationRow" style="display:none;">
                        <label>Maximum Carry Forward Leaves Allowed <span class="Mandetory">*</span></label>
                        @Html.TextBoxFor(a => a.Annual_MaximumEarnedLeaveAllowed, new { @class = "form-control" })
                    </div>
               
            </div>


           
        </div>

        @* Maternity Leave *@
        <div class="group-box anim" style="--delay: .3s">
            <h3>Maternity Leave</h3>
            <div class="row">
              
                <div class="col-md-4 form-group">
                    <label>Maximum Leaves Allocation Allowed (Weeks)<span class="Mandetory">*</span></label>
                    @Html.TextBoxFor(a => a.Maternity_MaximumLeaveAllocationAllowed, new { @class = "form-control", @required = "required" })
                </div>
                <div class="col-md-4 form-group">
                    <label>Applicable After Working Days <span class="Mandetory">*</span></label>
                    @Html.TextBoxFor(a => a.Maternity_ApplicableAfterWorkingDays, new { @class = "form-control", @required = "required" })
                </div>

                <div class="col-md-4 form-group">
                    <label> Apply Before How Many Weeks?  <span class="Mandetory">*</span></label><br />
                    @Html.TextBoxFor(a => a.Maternity_ApplyBeforeHowManyDays, new { @class = "form-control", @required = "required" })
                </div>
            </div>

            <div class="row">
                <div class="col-md-4 form-group">
                    <label>Document Required <span class="Mandetory">*</span></label><br />
                    @Html.CheckBoxFor(a => a.Maternity_MedicalDocument)
                </div>
            </div>
            <hr />
            @*  Adoption Leave *@
            <h3>Adoption</h3>
            <div class="row">
              
                <div class="col-md-4 form-group">
                    <label>Maximum Leaves Allocation Allowed (Weeks)<span class="Mandetory">*</span></label>
                    @Html.TextBoxFor(a => a.Adoption_MaximumLeaveAllocationAllowed, new { @class = "form-control", @required = "required" })
                </div>
                @* <div class="col-md-4 form-group">
                    <label>Applicable After Working Days <span class="Mandetory">*</span></label>
                    @Html.TextBoxFor(a => a.Adoption_ApplicableAfterWorkingDays, new { @class = "form-control", @required = "required" })
                </div> *@
            </div>
            <div class="row">
                <div class="col-md-4 form-group">
                    <label>Document Required <span class="Mandetory">*</span></label><br />
                    @Html.CheckBoxFor(a => a.Adoption_MedicalDocument)
                </div>
            
            </div>
            <hr />

            @* Miscarriage Leave *@
            <h3>Miscarriage</h3>
            <div class="row">
                
                <div class="col-md-4 form-group">
                    <label>Maximum Leaves Allocation Allowed (Weeks)<span class="Mandetory">*</span></label>
                    @Html.TextBoxFor(a => a.Miscarriage_MaximumLeaveAllocationAllowed, new { @class = "form-control", @required = "required" })
                </div>
            </div>  
            <div class="row">
                <div class="col-md-4 form-group">
                    <label>Document Required</label><br />
                    @Html.CheckBoxFor(a => a.Miscarriage_MedicalDocument)
                </div>
              
            </div>
        </div>

        <div class="group-box anim" style="--delay: .3s">
            <h3>Paternity</h3>
            <div class="row">
                <div class="col-md-4 form-group">
                    <label>Maximum Leaves Allocation Allowed  </label>
                    @Html.TextBoxFor(a => a.Paternity_maximumLeaveAllocationAllowed, new { @class = "form-control" })
                </div>


                <div class="col-md-4 form-group">
                    <label>Applicable After Working Months </label>
                    @Html.TextBoxFor(a => a.Paternity_applicableAfterWorkingMonth, new { @class = "form-control" })
                </div>
                <div class="col-md-4 form-group">
                    <label>Document Required <span class="Mandetory">*</span></label><br />
                    @Html.CheckBoxFor(a => a.Paternity_medicalDocument)
                </div>
                @* <div class="col-md-4 form-group">
                <label>IsActive</label><br />
                @Html.CheckBoxFor(a => a.Paternity_active)
                </div> *@
            </div>

            </div>

        @*   Camp Off *@
        <div class="group-box anim" style="--delay: .3s">
            <h3>Compensatory Leave</h3>
            <div class="row">
                <div class="col-md-4 form-group">
                    <label>Minimum Hours Of Work <span class="Mandetory">*</span></label>
                    @Html.TextBoxFor(a => a.CampOff_HoursOfWork, new { @class = "form-control", @required = "required" })
                </div>

                <div class="col-md-4 form-group">
                    <label> Expired In Days  <span class="Mandetory">*</span></label><br />
                    @Html.TextBoxFor(a => a.CampOff_ExpiryDate, new { @class = "form-control", @required = "required" })
                </div>
            </div>
           @*  <div class="row">
                
                <div class="col-md-4 form-group">
                    <label>Document Required <span class="Mandetory">*</span></label><br />
                    @Html.CheckBoxFor(a => a.CampOff_MedicalDocument)
                </div>
               
            </div> *@
        </div>

       
        <div class="row">
            <div class="col-md-8">
                <input type="submit" value="Submit" class="btn btn-success" />
                <input id="cancelButton" type="button" value="Cancel" class="btn btn-danger" />

            </div>
            
        </div>

    </div>

     

</form>
<script>
    document.getElementById('cancelButton').addEventListener('click', function () {
        window.location.href = '@Url.Action("LeavePolicyListing", "LeavePolicy")';
    });
</script>
<script>
    $(document).ready(function () {
        // Show or hide the "Maximum Earned Leaves Allocation Allowed" field based on checkbox state
        $('#carryForwardCheckbox').change(function () {
            if ($(this).is(':checked')) {
                $('#earnedLeaveAllocationRow').show();
            } else {
                $('#earnedLeaveAllocationRow').hide();
            }
        });

        // Trigger the change event on page load to handle pre-checked state
        $('#carryForwardCheckbox').trigger('change');
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        // Function to show or hide the "Document Required" checkbox based on medical leaves input
        function toggleDocumentRequired() {
            var medicalLeaves = parseInt($("#medicalLeaveInput").val(), 10);

            if (medicalLeaves > @Convert.ToInt32(MaxMedicalLeaveDoc.MaxMedicalDoc)) {
                $("#documentRequiredField").show();
            } else {
                $("#documentRequiredField").hide();
            }
        }

        // Call the function when the page loads
        toggleDocumentRequired();

        // Bind the function to the input change event
        $("#medicalLeaveInput").on("input", function () {
            toggleDocumentRequired();
        });
    });
</script>

HRMS.Web/HRMS.Web/Areas/Admin/Views/LeavePolicy/LeavePolicyDetailsListing.cshtml
@using HRMS.Models.Common;
<link href="~/assets/pages/gridlist.css" rel="stylesheet" />

@model Results
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Policy List";
    var success = TempData["Success"];
    var Err = TempData["Error"];
}
<div class="main-header anim" style="--delay: 0s">Policy List   <button type="button" class="btn btn-addBtn" id="openFormBtn">Add Policy</button> </div>
 

@* <div class="addcomp px-4">
    <h4>Leave Policy List</h4>
    <a href="~/Admin/LeavePolicy"> <button type="button" class="btn btn-addcompany" id="openFormBtn">Add Leave Policy</button></a>
</div> *@

<div class="table-responsive py-3">

    <table id="tblLeavePolicyDetailsListing" class="table table-striped body-text" style="width:100%">

        <thead>
            <tr>
                <th class="first" style="visibility:hidden"> /th>
                <th>Title</th>
                <th>Action</th>
            </tr>
        </thead>
    </table>
</div>



<script type="text/javascript">
    $(document).ready(function () {
        $('#tblLeavePolicyDetailsListing').DataTable({
            "ajax": {
                "url": "LeavePolicyDetailsListings/",
                "type": "POST",
                "datatype": "json"
            },
            "ordering": true,
            "paging": true,
            "searching": true,
            "info": true,
            "columns": [
                { "data": "id", "autoWidth": true },  // Ensure property name matches JSON response
                { "data": "title", "autoWidth": true },
                {
                    // Actions Column
                    mRender: function (data, type, row) {
                        var linkActions = `
                        <div class="table-data-feature">
                                <a data-toggle="tooltip" data-placement="top" class="item" href="LeavePolicyDetails?id=${row.encodedId}" title="Edit" data-original-title="Edit">
                                <img src="/assets/img/edit.png" width="20" height="20" />
                            </a>
                                <a data-toggle="tooltip" data-placement="top" class="item delete-btn" href="DeleteLeavesDetails?id=${row.encodedId}" title="Delete" data-original-title="Delete"  >
                                <img src="/assets/img/delete.png" width="20" height="20" />
                            </a>
                        </div>`;
                        return linkActions;
                    }
                },
            ],
            "columnDefs": [
                {
                    target: 2,
                    visible: false,
                    searchable: false
                },
                {
                    "targets": [0],
                    "orderable": false,
                    "visible": false
                },
                {
                    "targets": [1],
                    "orderable": true,
                    "defaultContent": " "
                }
            ],
            "responsive": true
        });

        // Add confirmation alert for delete action
        $(document).on('click', '.delete-btn', function (e) {         
            e.preventDefault(); // Prevent default behavior of the link
            var deleteUrl = $(this).attr('href'); // Get the href value for the delete URL
            var rowId = $(this).data('id'); // Get the ID from the data attribute

            // Display confirmation alert
            if (confirm(`Are you sure you want to delete the leave policy  ?`)) {
                // If confirmed, redirect to the delete URL
                window.location.href = deleteUrl;
            }
        });
    });


    document.getElementById('openFormBtn').addEventListener('click', function () {
        window.location.href = '@Url.Action("LeavePolicyDetails", "LeavePolicy")';
        });
</script>

HRMS.Web/HRMS.Web/Areas/Admin/Views/LeavePolicy/PolicyCategoryDetails.cshtml
@using HRMS.Models
@using HRMS.Models.Common
@using HRMS.Models.Employee
@model PolicyCategoryModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Leave Policy";
}

<div class="main-header anim" style="--delay: 0s">  Policy Category</div>
<form id="leaveForm" method="post" enctype="multipart/form-data">

    <div class="Container">

        <div class="group-box anim" style="--delay: .3s">
            @Html.HiddenFor(x => x.Companies)
            <input type="hidden" name="Id" value="@Model.Id">

            <div class="row">
                <div class="col-md-6 form-group">
                    <label>Company <span class="Mandetory">*</span></label>
                    @Html.DropDownList("CompanyID", new SelectList(Model.Companies, "CompanyID", "Name"), " -- Select Company -- ", new { @class = "form-control", placeholder = "" })
                </div>
                <div class="col-md-6 form-group">
                    <label>Title <span class="Mandetory">*</span></label>
                    @Html.TextBoxFor(a => a.Name, new { @class = "form-control", @required = "required" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <input type="submit" value="Submit" class="btn btn-success" />
                <input id="cancelButton" type="button" value="Cancel" class="btn btn-danger" />

            </div>
            
        </div>
    </div>
</form>


<script>
    document.getElementById('cancelButton').addEventListener('click', function () {
        window.location.href = '@Url.Action("PolicyCategoryListing", "LeavePolicy")';
    });

</script>