HRMS.Web/HRMS.Web/Areas/Admin/Controllers/ShiftTypeController.cs
using HRMS.Models.Common;
using HRMS.Models.ShiftType;
using HRMS.Web.BusinessLayer;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Results = HRMS.Models.Common.Results;

namespace HRMS.Web.Areas.Admin.Controllers
{
    [Area(Constants.ManageAdmin)]
    [Authorize]
    public class ShiftTypeController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IBusinessLayer _businessLayer;
        private readonly ICheckUserFormPermission _CheckUserFormPermission;
        public ShiftTypeController(ICheckUserFormPermission CheckUserFormPermission,IConfiguration configuration, IBusinessLayer businessLayer)
        {
            _configuration = configuration;
            _businessLayer = businessLayer;
            _CheckUserFormPermission = CheckUserFormPermission;
        }

        public IActionResult ShiftTypeListing()
        {
            var EmployeeID = GetSessionInt(Constants.EmployeeID);
            var RoleId = GetSessionInt(Constants.RoleID);

            var FormPermission = _CheckUserFormPermission.GetFormPermission(EmployeeID, (int)PageName.ShiftTypeListing);
            if (FormPermission.HasPermission == 0 && RoleId != (int)Roles.Admin && RoleId != (int)Roles.SuperAdmin)
            {
                HttpContext.Session.Clear();
                HttpContext.SignOutAsync();
                return RedirectToAction("Index", "Home", new { area = "" });
            }
            Results results = new Results();
            return View(results);
        }
        [HttpPost]
        [AllowAnonymous]
        public JsonResult ShiftTypeListings(string sEcho, int iDisplayStart, int iDisplayLength, string sSearch, string sortCol,
    string sortDir)
        {
            var columnMapping = new Dictionary<string, string>
    {
        {"shiftTypeID", "shiftTypeID"},
        {"shiftTypeName", "ShiftTypeName"},
        {"startTime", "startTime"},
        {"endTime", "endTime"},
        {"autoAttendance", "autoAttendance"}
    
    };

            ShiftTypeInputParans shiftTypeParams = new ShiftTypeInputParans();
            shiftTypeParams.CompanyID = Convert.ToInt64(HttpContext.Session.GetString(Constants.CompanyID));
            shiftTypeParams.DisplayStart = iDisplayStart;
            shiftTypeParams.DisplayLength = iDisplayLength;
            shiftTypeParams.Searching = string.IsNullOrEmpty(sSearch) ? null : sSearch;
            shiftTypeParams.SortCol = columnMapping.ContainsKey(sortCol) ? columnMapping[sortCol] : "shiftTypeID";
            shiftTypeParams.SortDir = string.IsNullOrEmpty(sortDir) ? "DESC" : sortDir.ToUpper();
            var data = _businessLayer.SendPostAPIRequest(shiftTypeParams, _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.ShiftType, APIApiActionConstants.GetAllShiftTypes), HttpContext.Session.GetString(Constants.SessionBearerToken), true).Result.ToString();
            var results = JsonConvert.DeserializeObject<Results>(data);
            return Json(new {
                draw = sEcho,
                recordsTotal = results.ShiftType.Select(x => x.TotalRecords).FirstOrDefault() ?? 0,
                recordsFiltered = results.ShiftType.Select(x => x.FilteredRecords).FirstOrDefault() ?? 0,
                data = results.ShiftType });
        }
        public IActionResult Index(string id)
        {
            ShiftTypeModel shiftTypeModel = new ShiftTypeModel();
            shiftTypeModel.CompanyID = Convert.ToInt64(HttpContext.Session.GetString(Constants.CompanyID));
            if (!string.IsNullOrEmpty(id))
            {
                shiftTypeModel.ShiftTypeID = Convert.ToInt64(id);
                var data = _businessLayer.SendPostAPIRequest(shiftTypeModel, _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.ShiftType, APIApiActionConstants.GetAllShiftTypes), HttpContext.Session.GetString(Constants.SessionBearerToken), true).Result.ToString();
                shiftTypeModel = JsonConvert.DeserializeObject<Results>(data).shiftTypeModel;
            }
            var holidayListData = _businessLayer.SendPostAPIRequest(shiftTypeModel, _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.Holiday, APIApiActionConstants.GetHolidayList), HttpContext.Session.GetString(Constants.SessionBearerToken), true).Result.ToString();
            if (holidayListData != null)
            {
                shiftTypeModel.HolidayList = JsonConvert.DeserializeObject<List<SelectListItem>>(holidayListData);
            }
            shiftTypeModel.WorkingHoursCalculationTypeList = new List<SelectListItem>
            {
                new SelectListItem { Value = "first_check_in_and_last_check_out", Text = "First check in and last check out" },
                new SelectListItem { Value = "every_check_in_and_check_out", Text = "Every check in and check out" }
            };

            return View(shiftTypeModel);
        }
        [HttpPost]
        public IActionResult Index(ShiftTypeModel shiftTypeModel)
        {
            if (ModelState.IsValid)
            {
                shiftTypeModel.CompanyID = Convert.ToInt64(HttpContext.Session.GetString(Constants.CompanyID));
                shiftTypeModel.UserID = Convert.ToInt64(HttpContext.Session.GetString(Constants.EmployeeID ));
                var data = _businessLayer.SendPostAPIRequest(shiftTypeModel, _businessLayer.GetFormattedAPIUrl(APIControllarsConstants.ShiftType, APIApiActionConstants.AddUpdateShiftType), HttpContext.Session.GetString(Constants.SessionBearerToken), true).Result.ToString();
                var results = JsonConvert.DeserializeObject<Result>(data);

                if (shiftTypeModel.ShiftTypeID > 0)
                {
                    return RedirectToActionPermanent(WebControllarsConstants.ShiftTypeListing, WebControllarsConstants.ShiftType);
                }
                else
                {
                    return RedirectToActionPermanent(WebControllarsConstants.ShiftTypeListing, WebControllarsConstants.ShiftType);
                }
            }
            else
            {
                return View(shiftTypeModel);
            }
        }
         
        private int GetSessionInt(string key)
        {
            return int.TryParse(HttpContext.Session.GetString(key), out var value) ? value : 0;
        }
    }
}

HRMS.Web/HRMS.Web/Areas/Admin/Views/ShiftType/Index.cshtml
@using HRMS.Models.ShiftType;
@model ShiftTypeModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Shift Type";
}

<div class="main-header anim" style="--delay: 0s">Shift Type Details </div>
<form method="post" enctype="multipart/form-data">
    <div class="Container">
        <div class="group-box anim" style="--delay: .3s">
            <div class="row">
@* 
        <div class="col-md-12 container-heading">
            <label class="form-label" style="font-weight:500;">  </label>
        </div> *@
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6 my-2">
                    <div class="col-md-12">
                        <label class="form-label"> Shift Type Name <span class="Mandetory">*</span> </label>
                    </div>
                    <div class="col-md-12">
                        @Html.HiddenFor(x => x.ShiftTypeID)
                        @Html.TextBoxFor(a => a.ShiftTypeName, new { @class = "form-control", @required = "required" })

                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6 my-2">
                    <div class="col-md-12">
                        <label class="form-label"> Shift Start Time (HH:MM:SS) <span class="Mandetory">*</span> </label>
                    </div>
                    <div class="col-md-12">
                        @Html.TextBoxFor(a => a.StartTime, new { type = "time", @class = "form-control", @required = "required", step = 1 })

                    </div>
                </div>
                <div class="col-md-6 my-2">
                    <div class="col-md-12">
                        <label class="form-label"> Shift End Time (HH:MM:SS) <span class="Mandetory">*</span> </label>
                    </div>
                    <div class="col-md-12">
                        @Html.TextBoxFor(a => a.EndTime, new { type = "time", @class = "form-control", @required = "required", step = 1 })

                    </div>
                </div>

                <div class="col-md-6 my-2">
                    <div class="col-md-12">
                        <label class="form-label"> Holiday List <span class="Mandetory">*</span> </label>
                    </div>
                    <div class="col-md-12">
                                <div class="position-relative">
                        @Html.DropDownListFor(model => model.HolidayID, Model.HolidayList, "-- Select Holiday --", new { @class = "form-control" })
                                <i class="fa fa-chevron-down position-absolute"
                                   style="font-size: 10px;color: gray; right: 10px; top: 50%; transform: translateY(-50%); pointer-events: none;"></i>
                                </div>
                    </div>
                </div>
                <div class="col-md-6 my-2">
                    <div class="col-md-12">
                        <label class="form-label"> Enable Auto Attendance <span class="Mandetory">*</span> </label>
                    </div>
                    <div class="col-md-12">

                        @Html.CheckBoxFor(a => a.AutoAttendance)
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12 container-heading">
            <label class="form-label" style="font-weight:500;"> Auto attendance settings</label>
        </div>
        <div class="col-md-12">


            <div class="row">


                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-6 my-2">
                            <div class="col-md-12">
                                <label class="form-label"> Determine check in and check out <span class="Mandetory">*</span> </label>
                            </div>
                            <div class="col-md-12">
                                @Html.CheckBoxFor(a => a.IsCheckInAndOut)
                            </div>
                        </div>


                        <div class="col-md-6 my-2">
                            <div class="col-md-12">
                                <label class="form-label"> Working hours calculation based on <span class="Mandetory">*</span> </label>
                            </div>
                            <div class="col-md-12">
                                @Html.DropDownListFor(model => model.WorkingHoursCalculation, Model.WorkingHoursCalculationTypeList, "-- Select --", new { @class = "form-control" })

                            </div>
                        </div>

                        <div class="col-md-6 my-2">
                            <div class="col-md-12">
                                <label class="form-label"> Working hour threashold half day (Minutes) <span class="Mandetory">*</span> </label>
                            </div>
                            <div class="col-md-12">

                                @Html.TextBoxFor(a => a.HalfDayWorkingHours, new { @type = "number", @class = "form-control", @min = "0", @step = "1" })
                            </div>
                        </div>

                        <div class="col-md-6 my-2">
                            <div class="col-md-12">
                                <label class="form-label"> Working hours threashold for absent (Minutes) <span class="Mandetory">*</span> </label>
                            </div>
                            <div class="col-md-12">

                                @Html.TextBoxFor(a => a.AbsentDayWorkingHours, new { @type = "number", @class = "form-control", @min = "0", @step = "1" })
                            </div>
                        </div>


                        <div class="col-md-6 my-2">
                            <div class="col-md-12">
                                <label class="form-label"> Begin Check in before shift time <span class="Mandetory">*</span> </label>
                            </div>
                            <div class="col-md-12">

                                @Html.CheckBoxFor(a => a.CheckInBeforeShift)
                            </div>
                        </div>

                        <div class="col-md-6 my-2">
                            <div class="col-md-12">
                                <label class="form-label"> Allow Check out after shift time <span class="Mandetory">*</span> </label>
                            </div>
                            <div class="col-md-12">

                                @Html.CheckBoxFor(a => a.CheckOutAfterShift)
                            </div>
                        </div>

                        <div class="col-md-6 my-2">
                            <div class="col-md-12">
                                <label class="form-label"> Process attendance after (Minutes) <span class="Mandetory">*</span></label>
                            </div>
                            <div class="col-md-12">

                                @Html.TextBoxFor(a => a.ProcessAttendanceAfter, new { @type = "number", @class = "form-control", @min = "0", @step = "1" })
                            </div>
                        </div>

                        <div class="col-md-6 my-2">
                            <div class="col-md-12">
                                <label class="form-label"> Last sync date and time <span class="Mandetory">*</span></label>
                            </div>
                            <div class="col-md-12">
                                @Html.TextBoxFor(a => a.LastSyncDateTime, "{0:yyyy-MM-ddTHH:mm}", new { type = "datetime-local", @class = "form-control", @min = "1900-01-01T00:00" })
                            </div>
                        </div>

                        <div class="col-md-6 my-2">
                            <div class="col-md-12">
                                <label class="form-label"> Mark auto attendance for holidays </label>
                            </div>
                            <div class="col-md-12">

                                @Html.CheckBoxFor(a => a.AutoAttendanceOnHoliday)
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12 my-2">
                        <div class="row">
                            <div class="col-md-6 my-2">
                                <div class="col-md-12">
                                    <label class="form-label">  Last entry grace period (Minutes) <span class="Mandetory">*</span> </label>
                                </div>
                                <div class="col-md-12">

                                    @Html.TextBoxFor(a => a.LastEntryGracePeriod, new { @type = "number", @class = "form-control", @min = "0", @step = "1" })
                                </div>
                            </div>
                            <div class="col-md-6 my-2">
                                <div class="col-md-12">
                                    <label class="form-label"> Early exit grace period (Minutes) <span class="Mandetory">*</span> </label>
                                </div>
                                <div class="col-md-12">

                                    @Html.TextBoxFor(a => a.EarlyExitGracePeriod, new { @type = "number", @class = "form-control", @min = "0", @step = "1" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12 my-2">
                        <div class="row">
                            <div class="col-md-12 my-2">
                                <div class="col-md-12">
                                    Comments
                                    <label class="form-label"> Comments </label>
                                </div>
                                <div class="col-md-12">
                                    @Html.TextAreaFor(a => a.Comments, new { @class = "form-control", placeholder = "Enter your comments", rows = "4" })
                                </div>
                            </div>


                        </div>
                    </div>
                </div>


                <div class="row">
                    &nbsp;
                </div>


              @*   <div class="row">
                    <div class="col-md-12 my-2">
                        <input style="float:right" type="submit" value="Submit" class="btn btn-success" />
                        <input id="cancelButton" style="float:right;margin-right: 10px;" type="button" value="Cancel" class="btn btn-success" />
                    </div>
                </div> *@
                        <div class="row">
                            <div class="col-md-12">
                                <input type="submit" value="Submit" class="btn btn-success" />
                                <button id="cancelButton" class="btn btn-danger" type="button" value="Cancel">Cancel</button>
                            </div>
                        </div>

            </div>
        </div>
            </div>
        </div>
    </div>
</form>

<script>
    document.getElementById('cancelButton').addEventListener('click', function () {
        window.location.href = '@Url.Action("ShiftTypeListing", "ShiftType")';
    });
</script>

HRMS.Web/HRMS.Web/Areas/Admin/Views/ShiftType/ShiftTypeListing.cshtml
@using HRMS.Models.Common;
<link href="~/assets/pages/gridlist.css" rel="stylesheet" />

@model Results
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Shift Type";

    var success = TempData["Success"];
    var Err = TempData["Error"];
}
<div class="main-header anim" style="--delay: 0s">Shift Type List  <a href="~/Admin/ShiftType"> <button type="button" class="btn btn-addBtn" id="openFormBtn">Add Shift Type</button></a></div>


<div class="table-responsive py-3">

    <table id="tblShiftTypeListing" class="table table-striped body-text" style="width:100%">

        <thead>
            <tr>
                <th class="first" style="visibility:hidden"> /th>
                <th>Shift Type Name</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Auto Attendance Enabled </th>
                <th>Action</th>
            </tr>
        </thead>

    </table>
</div>



<script type="text/javascript">

    $(document).ready(function () {
   
        $('#tblShiftTypeListing').DataTable({
            "processing": true,
            "serverSide": true,
            "ajax": {
                "url": "ShiftTypeListings/",
                "type": "POST",
                "datatype": "json",
                "data": function (d) {
                    var sortColumn = typeof d.order[0] !== 'undefined' ? d.columns[d.order[0].column].data : 'shiftTypeID';
                    var sortDirection = typeof d.order[0] !== 'undefined' ? d.order[0].dir : 'asc';
                     return {
                         sEcho: d.draw,
                         iDisplayStart: d.start,
                         iDisplayLength: d.length,
                         sSearch: d.search.value,
                         sortCol: sortColumn,
                         sortDir: sortDirection
                     };
                 }
            },
            "ordering": true,
            "paging": true,
            "searching": true,
            "info": true,
            "columns": [
                { "data": "shiftTypeID", "autoWidth": true, },
                { "data": "shiftTypeName", "autoWidth": true, },
                { "data": "startTime", "autoWidth": true, },
                { "data": "endTime", "autoWidth": true, },
                { "data": "autoAttendance", "autoWidth": true, },
                {
                    mRender: function (data, type, row) {

                        var linkEdit = '<div class="table-data-feature"><a data-toggle="tooltip" data-placement="top"  class="item" href="Index?id=' + row.shiftTypeID + '"  title=""  data-original-title="Edit"><img src="/assets/img/edit.png" width="20" height="20" /></a>';
                        return linkEdit;
                    }
                },
            ],
            "columnDefs": [
                {
                    target: 2,
                    visible: false,
                    searchable: false
                },

                {

                    "targets": [0], //first and last not sortable
                    "orderable": false,
                    "visible": false
                },

                {

                    "targets": [1], //first and last not sortable
                    "orderable": true,
                    "defaultContent": " "
                }

            ]
            , "responsive": true

        });


    });
</script>